### ISSUE TITLE
Error when I'm joining the server

### ISSUE THREAD

**Issue by hardixnph** [deaFPS/cs2-pug-lua#1]
Hi,

When I'm joining the server I get this error `Script Runtime Error: /home/container/game/csgo/scripts/vscripts/dea.lua:394: attempt to call method 'TimerExists' (a nil value)
stack traceback:
        /home/container/game/csgo/scripts/vscripts/dea.lua:394: in function </home/container/game/csgo/scripts/vscripts/dea.lua:390>` in my server console and that timer with **Waiting for players** doesn't work.

Thanks for your time.

**Comment by deaFPS** [comment]
make sure your folder structure is the same as in the github repo
TimerExists relies on the timers lua lib
