### ISSUE TITLE
Support colored messages with LuaHudcoreCS2

### ISSUE THREAD

**Issue by crashzk** [deaFPS/cs2-pug-lua#10]
It would be possible to implement color support in messages using [LuaHudcoreCS2](https://github.com/NickFox007/LuaHudcoreCS2#luahudcorecs2)?

I know that currently the script already supports colored messages, but using [LuaAdvertCS2](https://github.com/NickFox007/LuaAdvertCS2) we have a conflict with the message prefix, the message prefix is ​​duplicated.

![image](https://github.com/deaFPS/cs2-pug-lua/assets/32937653/41fc388c-2e44-454f-a776-495c21754594)

Then, if I deactivate the CS2 PUG Lua script, the message prefixes become normal again.

Anyway, I believe that adding support for making messages colored by LuaHudcoreCS2 will solve the problem. Or would there be a simpler fix?

**Comment by deaFPS** [comment]
should be conflicting anymore
