### ISSUE TITLE
Can you add this features?

### ISSUE THREAD

**Issue by iAnvar** [deaFPS/cs2-pug-lua#11]
1) Can you add a function that will show the player is ready after using the player_ping command in the chat. 
For example:
[after use player_ping] Player1 is ready!
[If he uses it again] Player1 is not ready!

2) And can you add autokick for afk players and penalties for left the game after it starts like ban for 5-10-20 minutes

3) Please add pugban command

**Comment by crashzk** [comment]
Bans can try to use - https://github.com/Pisex/cs2-bans

Issue of AFK Players and Penalties for players who abandon the match, I believe a separate script/plugin would be better.

**Comment by iAnvar** [comment]
> Bans can try to use - https://github.com/Pisex/cs2-bans
> 
> Issue of AFK Players and Penalties for players who abandon the match, I believe a separate script/plugin would be better.

thanks

**Comment by deaFPS** [comment]
1. is already added but has to be activated via pug_cfg
2. for a sophisticated ban system use a MM plugin as lua is very limited
