### ISSUE TITLE
Cannot use any commands 

### ISSUE THREAD

**Issue by xFlum3** [deaFPS/cs2-pug-lua#13]
Hey, i installed an clean server with the files you said required and also your pug files but commands is not working

**Comment by crashzk** [comment]
Installed [Metamod](https://www.sourcemm.net/downloads.php?branch=dev)?

**Comment by deaFPS** [comment]
> Hey, i installed an clean server with the files you said required and also your pug files but commands is not working

make sure your vscript is unlocked and you exec pugplugin.cfg after vscript is initialized
