### ISSUE TITLE
Suggestions:

### ISSUE THREAD

**Issue by MasterWindowS** [deaFPS/cs2-pug-lua#14]
Hi, I wanted to see if you could add a knife only round and have the winner choose sides (CT OR TT).

**Comment by MasterWindowS** [comment]
And if you can put the command !ready in the chat pls

**Comment by crashzk** [comment]
Duplicate https://github.com/deaFPS/cs2-pug-lua/issues/5

> chat commands aren't possible via the lua api
> 
> players can ready up using the ping feature (middle mouse click)
> 
> to pause a match you can either use a admin command or just call a regular timeout through the ESC menu (you can change how many timeouts and how long they shall be in the pug_cfg file)
> 
> for any of the admin commands to work you need to login using `adminlogin 123` (123 is the default password) via the client

**Comment by MasterWindowS** [comment]
And add a cfg that is to add admins without having to enter the adminlogin? Because I already see some people passing the command and it wouldn't be very good to have to change the password every time.

Like the admins_simple.ini

**Comment by MasterWindowS** [comment]
Oh will see, okey. Thanks <3
