### ISSUE TITLE
improvements

### ISSUE THREAD

**Issue by strteamservidores** [deaFPS/cs2-pug-lua#2]
add the .ready or .r command, such as .pause, .unpause.
add knife round on the start to define what team will be CT or T
add infinity money on warmup

**Comment by deaFPS** [comment]
chat commands aren't possible via the lua api

players can ready up using the ping feature (middle mouse click)

to pause a match you can either use a admin command or just call a regular timeout through the ESC menu (you can change how many timeouts and how long they shall be in the pug_cfg file)

for any of the admin commands to work you need to login using `adminlogin 123` (123 is the default password) via the client
