### ISSUE TITLE
Can't connect to the server if i load the script

### ISSUE THREAD

**Issue by wavypzuto** [deaFPS/cs2-pug-lua#3]
Hi
Im having if this issue, if i load the pug lua script everyone cant join the server

Example:
[#4065060375 UDP steamid:76561198241769606@27.79.208.223:63649] closed by app, linger requested but not needed (2039) NETWORK_DISCONNECT_KICKED
Removing Steam Net Connection for 27.79.208.223:63649, handle #4065060375
CloseSteamNetConnection handle #4065060375 (userdata -1)
Removing Steam Net Connection for 27.79.208.223:63649, handle #4065060375

When i connect it just and then turn back to the main screen of the game
Can you help me fix this, thank you!

**Comment by deaFPS** [comment]
either disable the whitelist or add your steamid3 to the whitelist
