### ISSUE TITLE
Auto Start when 10 players type ready

### ISSUE THREAD

**Issue by crashzk** [deaFPS/cs2-pug-lua#6]
It would be interesting to add an option to auto start the competition when all 10 players are ready, not wait for an admin to start the pug.

**Comment by iAnvar** [comment]
This is how it works, I checked it yesterday

**Comment by deaFPS** [comment]
> It would be interesting to add an option to auto start the competition when all 10 players are ready, not wait for an admin to start the pug.

players can ready up, the game will start once all players are ready
