### ISSUE TITLE
Fixed waiting for players message

### ISSUE THREAD

**Issue by crashzk** [deaFPS/cs2-pug-lua#8]
Message waiting for players, would it be possible to leave it fixed in the HUD message?

![image](https://github.com/deaFPS/cs2-pug-lua/assets/32937653/601fdb5c-390a-47b2-b4ea-2b2a2735af11)

The chat message would remain in the flood, but the HUD Center message would remain fixed until the 10 players were ready and the pug began.

It would be possible? I believe this makes it easier for the player to identify how many players are missing and such.

**Comment by deaFPS** [comment]
made the interval only affect the chat and not the ui msg, thx for the headsup!
