### ISSUE TITLE
Add TAG Name Ready & NotReady

### ISSUE THREAD

**Issue by crashzk** [deaFPS/cs2-pug-lua#9]
Would it be possible to add a TAG to the players' nicknames for those who gave Ready and NotReady?

**Comment by deaFPS** [comment]
not in lua

**Comment by crashzk** [comment]
@deaFPS support for TAGS would not be possible, but would there be any way to notify/mark the player that it is notready or ready?

Be it a message in the chat when the player is ready or becomes notready again. I ask because many players are having problems knowing whether they are ready or not.

And as incredible as it may seem, many don't even know what PING would be to make it ready. It would also be interesting that in addition to the ping option, leaving the option for the user to type in the console even ready, notready would also be a good option.

**Comment by deaFPS** [comment]
> @deaFPS support for TAGS would not be possible, but would there be any way to notify/mark the player that it is notready or ready?
> 
> Be it a message in the chat when the player is ready or becomes notready again. I ask because many players are having problems knowing whether they are ready or not.

the chat will already print out who ready'd and who un-redy'd if you enable autokickOnMapChange

**Comment by crashzk** [comment]
> > @deaFPS support for TAGS would not be possible, but would there be any way to notify/mark the player that it is notready or ready?
> > Be it a message in the chat when the player is ready or becomes notready again. I ask because many players are having problems knowing whether they are ready or not.
> 
> the chat will already print out who ready'd and who un-redy'd if you enable autokickOnMapChange

I'll test... In any case, activating this feature whenever the map changes, the players will be kicked, correct?

In this case, I would like to show the message without kicking the players.
